# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-27 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='国内名校', max_length=20, verbose_name='机构标签'),
        ),
    ]
