# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-24 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='url',
            field=models.CharField(default='https://www.cnblogs.com/guigujun', max_length=200, verbose_name='访问地址'),
        ),
    ]
