# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-24 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20180224_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(default='考试洛', max_length=300, verbose_name='老师告诉你'),
        ),
        migrations.AddField(
            model_name='course',
            name='you_need_know',
            field=models.CharField(default='爱学习', max_length=300, verbose_name='课程须知'),
        ),
    ]
