# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-25 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20180224_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='https://www.cnblogs.com/guigujun', max_length=200, verbose_name='访问地址'),
        ),
    ]
