# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-27 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180226_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nike_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='昵称'),
        ),
    ]
