# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-28 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180227_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='server_tel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='服务电话'),
        ),
    ]
