# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-28 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofile_server_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server_Tel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='服务电话')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='server_tel',
        ),
    ]
